### ISSUE TITLE
Coeficiente Paypal

### ISSUE THREAD

**Issue by andersonnarciso** [AndersonFranco/woocommerce-installments#3]
Olá Anderson, beleza? Cara sabemos que o paypal também adiciona porcentagem em cima do valor das parcelas igual ao pagseguro, sabes qual seria o coeficiente deles? Ou onde adicionar 2.39% em cada parcela?

**Comment by AndersonFranco** [comment]
Opa, td blz?! Segue o link de uma calculadora que criei pra você. Basta informar a taxa desejada (2.39) e clicar em calcular. Acredito que a precisão esteja ok, mas é bom validar. Use por sua conta e risco! rs Abraços.
 
http://andersonfranco.github.io/capital-recovery-factor/

**Comment by andersonnarciso** [comment]
Pow que massa cara, parabéns pelas duas ferramentas! Na real acho que não está precisa, pois um exemplo R$180.00 / 12 = 15 + 2.39% = R$15.35, se utilizo o coeficiente da calculadora o valor vai a R$17.43

**Comment by andersonnarciso** [comment]
Eu dei uma acrecentada no teu código para que fizece isso automatico sem utilizar o coeficiente

http://pastebin.com/Ynzkca0w

Só que  tem um porém, ele arredonda o valor para mais, só não achei onde no código você programou para arredondar os valores

**Comment by AndersonFranco** [comment]
Só para efeito de registro, a conversa segue em
https://github.com/AndersonFranco/woocommerce-installments/issues/4
